apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-express-app.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: ""   # optional, leave empty for global IP
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "my-express-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
